#############################################################################
# Makefile for building: bin/debug/InternetRadioPlayer
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  InternetRadioPlayer.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt5/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile InternetRadioPlayer.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I. -Isrc/includes -Iimport -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtSql -isystem /usr/include/i386-linux-gnu/qt5/QtNetwork -isystem /usr/include/i386-linux-gnu/qt5/QtCore -Ibuild/debug/InternetRadioPlayer/moc
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -L/media/sf_repository/InternetRadioPlayer//lib.// -lbass -lQt5Sql -lQt5Network -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/debug/InternetRadioPlayer/obj/

####### Files

SOURCES       = src/main.cpp \
		src/RadioClient.cpp \
		src/RadioPlayer.cpp \
		src/RadioPlayerStream.cpp \
		src/RadioServer.cpp \
		src/MusicStreamsBase.cpp build/debug/InternetRadioPlayer/moc/moc_RadioClient.cpp \
		build/debug/InternetRadioPlayer/moc/moc_RadioPlayer.cpp \
		build/debug/InternetRadioPlayer/moc/moc_RadioPlayerStream.cpp \
		build/debug/InternetRadioPlayer/moc/moc_RadioServer.cpp \
		build/debug/InternetRadioPlayer/moc/moc_MusicStreamsBase.cpp
OBJECTS       = build/debug/InternetRadioPlayer/obj/main.o \
		build/debug/InternetRadioPlayer/obj/RadioClient.o \
		build/debug/InternetRadioPlayer/obj/RadioPlayer.o \
		build/debug/InternetRadioPlayer/obj/RadioPlayerStream.o \
		build/debug/InternetRadioPlayer/obj/RadioServer.o \
		build/debug/InternetRadioPlayer/obj/MusicStreamsBase.o \
		build/debug/InternetRadioPlayer/obj/moc_RadioClient.o \
		build/debug/InternetRadioPlayer/obj/moc_RadioPlayer.o \
		build/debug/InternetRadioPlayer/obj/moc_RadioPlayerStream.o \
		build/debug/InternetRadioPlayer/obj/moc_RadioServer.o \
		build/debug/InternetRadioPlayer/obj/moc_MusicStreamsBase.o
DIST          = /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		InternetRadioPlayer.pro src/main.cpp \
		src/RadioClient.cpp \
		src/RadioPlayer.cpp \
		src/RadioPlayerStream.cpp \
		src/RadioServer.cpp \
		src/MusicStreamsBase.cpp
QMAKE_TARGET  = InternetRadioPlayer
DESTDIR       = bin/debug/#avoid trailing-slash linebreak
TARGET        = bin/debug/InternetRadioPlayer


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@test -d bin/debug/ || mkdir -p bin/debug/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: InternetRadioPlayer.pro /usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		InternetRadioPlayer.pro \
		/usr/lib/i386-linux-gnu/libQt5Sql.prl \
		/usr/lib/i386-linux-gnu/libQt5Core.prl \
		/usr/lib/i386-linux-gnu/libQt5Network.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile InternetRadioPlayer.pro
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf:
InternetRadioPlayer.pro:
/usr/lib/i386-linux-gnu/libQt5Sql.prl:
/usr/lib/i386-linux-gnu/libQt5Core.prl:
/usr/lib/i386-linux-gnu/libQt5Network.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile InternetRadioPlayer.pro

qmake_all: FORCE

dist: 
	@test -d build/debug/InternetRadioPlayer/obj/InternetRadioPlayer1.0.0 || mkdir -p build/debug/InternetRadioPlayer/obj/InternetRadioPlayer1.0.0
	$(COPY_FILE) --parents $(DIST) build/debug/InternetRadioPlayer/obj/InternetRadioPlayer1.0.0/ && $(COPY_FILE) --parents lib/bass.h src/includes/RadioClient.h src/includes/RadioPlayer.h src/includes/RadioPlayerStream.h src/includes/RadioServer.h src/includes/MusicStreamsBase.h src/includes/DataStructures.h build/debug/InternetRadioPlayer/obj/InternetRadioPlayer1.0.0/ && $(COPY_FILE) --parents src/main.cpp src/RadioClient.cpp src/RadioPlayer.cpp src/RadioPlayerStream.cpp src/RadioServer.cpp src/MusicStreamsBase.cpp build/debug/InternetRadioPlayer/obj/InternetRadioPlayer1.0.0/ && (cd `dirname build/debug/InternetRadioPlayer/obj/InternetRadioPlayer1.0.0` && $(TAR) InternetRadioPlayer1.0.0.tar InternetRadioPlayer1.0.0 && $(COMPRESS) InternetRadioPlayer1.0.0.tar) && $(MOVE) `dirname build/debug/InternetRadioPlayer/obj/InternetRadioPlayer1.0.0`/InternetRadioPlayer1.0.0.tar.gz . && $(DEL_FILE) -r build/debug/InternetRadioPlayer/obj/InternetRadioPlayer1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) bin/debug/$(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: build/debug/InternetRadioPlayer/moc/moc_RadioClient.cpp build/debug/InternetRadioPlayer/moc/moc_RadioPlayer.cpp build/debug/InternetRadioPlayer/moc/moc_RadioPlayerStream.cpp build/debug/InternetRadioPlayer/moc/moc_RadioServer.cpp build/debug/InternetRadioPlayer/moc/moc_MusicStreamsBase.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/debug/InternetRadioPlayer/moc/moc_RadioClient.cpp build/debug/InternetRadioPlayer/moc/moc_RadioPlayer.cpp build/debug/InternetRadioPlayer/moc/moc_RadioPlayerStream.cpp build/debug/InternetRadioPlayer/moc/moc_RadioServer.cpp build/debug/InternetRadioPlayer/moc/moc_MusicStreamsBase.cpp
build/debug/InternetRadioPlayer/moc/moc_RadioClient.cpp: src/includes/RadioClient.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_repository/InternetRadioPlayer -I/media/sf_repository/InternetRadioPlayer/src/includes -I/media/sf_repository/InternetRadioPlayer/import -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtSql -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/i386-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/i586-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/i586-linux-gnu/4.9/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include src/includes/RadioClient.h -o build/debug/InternetRadioPlayer/moc/moc_RadioClient.cpp

build/debug/InternetRadioPlayer/moc/moc_RadioPlayer.cpp: src/includes/DataStructures.h \
		import/bass.h \
		src/includes/RadioPlayer.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_repository/InternetRadioPlayer -I/media/sf_repository/InternetRadioPlayer/src/includes -I/media/sf_repository/InternetRadioPlayer/import -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtSql -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/i386-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/i586-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/i586-linux-gnu/4.9/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include src/includes/RadioPlayer.h -o build/debug/InternetRadioPlayer/moc/moc_RadioPlayer.cpp

build/debug/InternetRadioPlayer/moc/moc_RadioPlayerStream.cpp: src/includes/RadioPlayer.h \
		src/includes/DataStructures.h \
		import/bass.h \
		src/includes/MusicStreamsBase.h \
		src/includes/RadioPlayerStream.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_repository/InternetRadioPlayer -I/media/sf_repository/InternetRadioPlayer/src/includes -I/media/sf_repository/InternetRadioPlayer/import -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtSql -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/i386-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/i586-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/i586-linux-gnu/4.9/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include src/includes/RadioPlayerStream.h -o build/debug/InternetRadioPlayer/moc/moc_RadioPlayerStream.cpp

build/debug/InternetRadioPlayer/moc/moc_RadioServer.cpp: src/includes/RadioServer.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_repository/InternetRadioPlayer -I/media/sf_repository/InternetRadioPlayer/src/includes -I/media/sf_repository/InternetRadioPlayer/import -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtSql -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/i386-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/i586-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/i586-linux-gnu/4.9/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include src/includes/RadioServer.h -o build/debug/InternetRadioPlayer/moc/moc_RadioServer.cpp

build/debug/InternetRadioPlayer/moc/moc_MusicStreamsBase.cpp: src/includes/DataStructures.h \
		src/includes/MusicStreamsBase.h
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/media/sf_repository/InternetRadioPlayer -I/media/sf_repository/InternetRadioPlayer/src/includes -I/media/sf_repository/InternetRadioPlayer/import -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtSql -I/usr/include/i386-linux-gnu/qt5/QtNetwork -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/i386-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/i586-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/i586-linux-gnu/4.9/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include src/includes/MusicStreamsBase.h -o build/debug/InternetRadioPlayer/moc/moc_MusicStreamsBase.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

build/debug/InternetRadioPlayer/obj/main.o: src/main.cpp src/includes/RadioPlayerStream.h \
		src/includes/RadioPlayer.h \
		src/includes/DataStructures.h \
		import/bass.h \
		src/includes/MusicStreamsBase.h \
		src/includes/RadioServer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/InternetRadioPlayer/obj/main.o src/main.cpp

build/debug/InternetRadioPlayer/obj/RadioClient.o: src/RadioClient.cpp src/includes/RadioClient.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/InternetRadioPlayer/obj/RadioClient.o src/RadioClient.cpp

build/debug/InternetRadioPlayer/obj/RadioPlayer.o: src/RadioPlayer.cpp src/includes/RadioPlayer.h \
		src/includes/DataStructures.h \
		import/bass.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/InternetRadioPlayer/obj/RadioPlayer.o src/RadioPlayer.cpp

build/debug/InternetRadioPlayer/obj/RadioPlayerStream.o: src/RadioPlayerStream.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/InternetRadioPlayer/obj/RadioPlayerStream.o src/RadioPlayerStream.cpp

build/debug/InternetRadioPlayer/obj/RadioServer.o: src/RadioServer.cpp src/includes/RadioServer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/InternetRadioPlayer/obj/RadioServer.o src/RadioServer.cpp

build/debug/InternetRadioPlayer/obj/MusicStreamsBase.o: src/MusicStreamsBase.cpp src/includes/MusicStreamsBase.h \
		src/includes/DataStructures.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/InternetRadioPlayer/obj/MusicStreamsBase.o src/MusicStreamsBase.cpp

build/debug/InternetRadioPlayer/obj/moc_RadioClient.o: build/debug/InternetRadioPlayer/moc/moc_RadioClient.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/InternetRadioPlayer/obj/moc_RadioClient.o build/debug/InternetRadioPlayer/moc/moc_RadioClient.cpp

build/debug/InternetRadioPlayer/obj/moc_RadioPlayer.o: build/debug/InternetRadioPlayer/moc/moc_RadioPlayer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/InternetRadioPlayer/obj/moc_RadioPlayer.o build/debug/InternetRadioPlayer/moc/moc_RadioPlayer.cpp

build/debug/InternetRadioPlayer/obj/moc_RadioPlayerStream.o: build/debug/InternetRadioPlayer/moc/moc_RadioPlayerStream.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/InternetRadioPlayer/obj/moc_RadioPlayerStream.o build/debug/InternetRadioPlayer/moc/moc_RadioPlayerStream.cpp

build/debug/InternetRadioPlayer/obj/moc_RadioServer.o: build/debug/InternetRadioPlayer/moc/moc_RadioServer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/InternetRadioPlayer/obj/moc_RadioServer.o build/debug/InternetRadioPlayer/moc/moc_RadioServer.cpp

build/debug/InternetRadioPlayer/obj/moc_MusicStreamsBase.o: build/debug/InternetRadioPlayer/moc/moc_MusicStreamsBase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/InternetRadioPlayer/obj/moc_MusicStreamsBase.o build/debug/InternetRadioPlayer/moc/moc_MusicStreamsBase.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

